### ISSUE TITLE
Write tutorial for downloading solid edge

### ISSUE THREAD

**Issue by emmapaczkowski** [queens-satellite-team/Space-School#1]
We are going to want to make sure that students can download solid edge. Find the steps somewhere and  test that they will work and link the instructions in the appropriate spot in this repo.

**Comment by SeanTedesco** [comment]
Students download SolidWorks for their Mechanics and graphics course. Tye also wrote a SolidWorks beginners guide to assist in the first steps. The issue can be closed.
