### ISSUE TITLE
Write tutorial to convert a .stl file into a 3d pint file

### ISSUE THREAD

**Issue by SeanTedesco** [queens-satellite-team/Space-School#10]
**https://www.tomshardware.com/how-to/3d-print-an-stl-file**

**Comment by spacemansears** [comment]
This would be a useful tutorial, but do you feel we need to write a tutorial if this website already does it? Also, do some 3D printers not take .stl files?

I should add that if we are making our own models, we should avoid .stl files. Newer formats have become more popular and are more accurate.

**Comment by SeanTedesco** [comment]
I was not aware of these newer formats until now (3MF and AMF)!  This is really good to note going forward as it appears the team is 3d-printing some test setups for their sub-systems. 

I agree that we do not need to write our own tutorial. Emma and I recently did some printing following this tutorial and it was very straightforward. We can provide resources like this in a resource page for Space School or even a Space School Wiki if we want to take the time to do so; however, this is a different issue altogether. Closing this issue.
